### ISSUE TITLE
Why strip the input?

### ISSUE THREAD

**Issue by codecop** [SamirTalwar/Smoke#6]
approx line 81 `.collect { |_, type, file| [type, IO.read(file).strip] }` strips the input. This makes it impossible to send content with a leading empty line to the system under test. Also it makes it impossible to send a single CR/LF to it. Maybe input should be verbatim, so used exactly as is?

**Comment by SamirTalwar** [comment]
Agreed. I'm happy to remove it if it doesn't break the existing test cases (or if the break is because the test is broken).

**Comment by SamirTalwar** [comment]
I attempted this yesterday but unfortunately it was a pain because the code to process test results is mangled with the code to manage colours and such. It needs a chunk of refactoring first to split up the responsibilities.

Would you like to pair on it?

**Comment by codecop** [comment]
Sure. Imho `read_tests` needs some work too, a monster chain this is. I am available next week Mon any time and Tues evening or both. Pls just send an invite/Google cal.

**Comment by SamirTalwar** [comment]
Good news: I rewrote this [in Haskell](https://github.com/SamirTalwar/Smoke/tree/haskell), and it incidentally fixes this issue.

Bad news: it will probably not work on Windows. I need to try it.

if you feel like trying to run it yourself, you should just be able to [install Stack](https://haskellstack.org/) and run the relevant commands from the Makefile. (I imagine the Makefile itself won't work on Windows.)

**Comment by SamirTalwar** [comment]
Update: works on Windows now. 😀

**Comment by SamirTalwar** [comment]
I think https://github.com/SamirTalwar/Smoke/pull/8 fixes this, so I'm closing the issue. Feel free to re-open it if it's still a problem.

**Comment by SamirTalwar** [comment]
I think https://github.com/SamirTalwar/Smoke/pull/8 fixes this, so I'm closing the issue. Feel free to re-open it if it's still a problem.
