### ISSUE TITLE
Update to newer nixpkgs revision to support aarch64-darwin

### ISSUE THREAD

**Issue by andir** [SamirTalwar/smoke#64]
It would  be great if you could upgrade to a newer nixpkgs version. In particular one from the last couple of months. The reason for it being aarch64-darwin support which is becoming more and more common.

Within [`npmlock2nix`](https://github.com/nix-community/npmlock2nix) we are using some for our integration tests and some users/contributors are on aarch64-darwin. Unfortunately passing a newer `nixpkgs` instance via the `pkgs` attribute of your `default.nix` doesn't entirely cut it. This leads to some weird Haskell errors that I can't make any sense of (as a non-haskell developer).

**Comment by SamirTalwar** [comment]
(Decided I might as well merge that, so please test against trunk.)

**Comment by andir** [comment]
Looks better. Ran into some issues while compiling GHC but haven't figured out if that is just flaky due to the lack of a proper sandbox.

**Comment by SamirTalwar** [comment]
OK, glad to hear that it's looking better, at least. Please close the issue when you're sure.

**Comment by SamirTalwar** [comment]
Closing this; assuming it works well now.
