### ISSUE TITLE
Compatibility with alpine linux

### ISSUE THREAD

**Issue by 9SMTM6** [SamirTalwar/smoke#77]
First of all, thanks for this tool! It works very well, and severely underrated in terms of popularity IMO.

I've been using this to test my own solutions for the worksheets I make in my tutor job at my college, since apparently I cant be trusted with writing them right;-).

However while running this locally on windows or my regular linux works well, I stumbled when trying to use it in my gitlab pipeline via your prebuild binary, where I am using alpine images for the different tasks.

Concretely, after downloading the provided executable for linux to the right directory and making it executable I'm getting this:

```sh
Exec format error (os error 8)
```

I'm not entirely certain why its failing, not that experienced of a system programmer, my first guess was that smoke relies upon shared libraries that dont exist, prominently glibc instead of musl which alpine has, but at least installing gcompat (https://wiki.alpinelinux.org/wiki/Running_glibc_programs) didnt fix that.

I'm still looking for the issue or another fix so this is unknown as of now, and in general I will find an easy fix, but I just wanted to let you know that perhaps something could be done there, even if just documenting alternatives.

Gotta leave the train now, thanks for your time

**Comment by 9SMTM6** [comment]
Got it running in alpine by installing both gcompat and gmp (which I found via readelf).

**Comment by SamirTalwar** [comment]
I'm really glad you got it working! I'll add something along those lines to the README.

I'd be up for building for Alpine if GitHub Actions had an easy way to do it, but I think it'd require reworking the CI to build stuff in Docker, and I don't think I'll get around to doing that soon.

**Comment by SamirTalwar** [comment]
Finally got around to documenting this in the [README](https://github.com/SamirTalwar/smoke#readme). Thanks again!
