### ISSUE TITLE
Remove outdated stack configuration

### ISSUE THREAD

**Issue by jonaprieto** [SamirTalwar/smoke#86]
https://github.com/haskell/tar/pull/26 has been merged some time ago.

https://github.com/SamirTalwar/smoke/blob/2ee73564bf28896ddb8f6cbb117a78b663c77d3e/stack.yaml#L8-L12

**Comment by SamirTalwar** [comment]
Merged, yes, but not released. [The latest released version is v0.5.1.1](https://hackage.haskell.org/package/tar), which does not contain this commit.

**Comment by SamirTalwar** [comment]
Not one that I know of. I'd be happy to use an alternative.
