### ISSUE TITLE
Run tests from within the test file's directory

### ISSUE THREAD

**Issue by jonaprieto** [SamirTalwar/smoke#88]
Let Smoke discover and run all the tests available within a folder. The flag can be `--execdir` as in shelltestrunner. One optional flag could be `-r --recursive` if one wants to traverse the whole input directory.

The user may want to provide the extension for the test files to perform the search. I suggest having the suffix `.smoke.yaml` for this. The option flag can be `--extension`.

**Comment by SamirTalwar** [comment]
You can point it to a directory, and it'll find all the YAML files in there, or you can just pass it a bunch of arguments (or a glob):

```
$ smoke test/*.smoke.yaml
```

**Comment by SamirTalwar** [comment]
Glob expansion is a feature of your shell, not Smoke. `echo tests/*.smoke.yaml` will yield the same error.

You can try a recursive glob (I don't know if fish supports this):

```shell
$ smoke tests/**/*.smoke.yaml
```

Or you can use the output of `find`:

```shell
$ smoke $(find tests -name '*.smoke.yaml')
```

**Comment by SamirTalwar** [comment]
Great. I'll improve the docs and then close this issue.
